#!/bin/bash
# Краткие команды запуска разных вариантов Airflow

echo " Варианты запуска ML Pipeline Airflow:"
echo ""
echo "1. SQLite + SequentialExecutor (порт 8081):"
echo " ./scripts/airflow/start_airflow_sqlite_8081.sh"
echo ""
echo "2. PostgreSQL + LocalExecutor (порт 8082):"
echo " ./scripts/airflow/start_airflow_postgres_8082.sh"
echo ""
echo "3. Docker + PostgreSQL + LocalExecutor (порт 8083):"
echo " ./scripts/airflow/start_airflow_docker_8083.sh"
echo ""
echo " Web интерфейсы:"
echo " • SQLite: http://localhost:8081"
echo " • PostgreSQL: http://localhost:8082"
echo " • Docker: http://localhost:8083"
echo ""
echo " Логин/пароль для всех вариантов: admin/admin"
echo ""
echo "⏹️ Остановка:"
echo " • SQLite: Ctrl+C в терминале"
echo " • PostgreSQL: Ctrl+C в терминале"
echo " • Docker: ./scripts/airflow/stop_airflow_docker.sh"
